doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(resolve:DATABASE_URL)'
        port: '%env(resolve:DATABASE_PORT)'
        dbname: '%env(resolve:DATABASE_NAME)'
        user: '%env(resolve:DATABASE_USER)'
        password: '%env(resolve:DATABASE_PASS)'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
             numeric_functions:
                 rand: DoctrineExtensions\Query\Mysql\Rand
         