<?php

namespace AppBundle\Repository;

/**
 * AnimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeRepository extends \Doctrine\ORM\EntityRepository
{
}
