<?php

namespace AppBundle\Repository;

/**
 * BaguetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaguetteRepository extends \Doctrine\ORM\EntityRepository
{
}