<?php

namespace AppBundle\Repository;

/**
 * DVARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DVARepository extends \Doctrine\ORM\EntityRepository
{
}
