<?php

namespace AppBundle\Repository;

/**
 * HentaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HentaiRepository extends \Doctrine\ORM\EntityRepository
{
}
