<?php

namespace AppBundle\Repository;

/**
 * HugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HugRepository extends \Doctrine\ORM\EntityRepository
{
}
