<?php

namespace AppBundle\Repository;

/**
 * NekoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NekoRepository extends \Doctrine\ORM\EntityRepository
{
}
