<?php

namespace AppBundle\Repository;

/**
 * TrapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrapRepository extends \Doctrine\ORM\EntityRepository
{
}
