<?php

namespace AppBundle\Repository;

/**
 * YuriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YuriRepository extends \Doctrine\ORM\EntityRepository
{
}
