<?php

namespace App\Repository;

/**
 * NSFWNekoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NSFWNekoRepository extends \Doctrine\ORM\EntityRepository
{
}
